services:
  todo-db:
    image: postgres:latest
    container_name: todo-db
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
  todo:
    build: todo
    container_name: todo
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - APP_SECRET=secret
      - APP_ID=1
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - HTTP_SERVER_TIMEOUT=4s
      - HTTP_SERVER_IDLE_TIMEOUT=60s
      - POSTGRES_DB_HOST=todo-db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME=todo
      - POSTGRES_DB_USERNAME=user
      - POSTGRES_DB_PASSWORD=password
      - CLIENT_SSO_ADDRESS=sso:8080
      - CLIENT_SSO_TIMEOUT=10s
      - CLIENT_SSO_RETRIES_COUNT=3
    depends_on:
      - sso
      - todo-db
  sso-db:
    image: postgres:latest
    container_name: sso-db
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sso
    ports:
      - "5433:5432"
    volumes:
      - sso_pg_data:/var/lib/postgresql/data
  sso:
    build: sso
    container_name: sso
    ports:
      - "8081:8080"
    depends_on:
      - sso-db
    environment:
      - ENV=local
      - TOKEN_TTL=1h
      - SALT=jh5jL1hrb4hj
      - GRPC_SERVER_PORT=8080
      - GRPC_SERVER_TIMEOUT=10s
      - POSTGRES_DB_HOST=sso-db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME=sso
      - POSTGRES_DB_USERNAME=user
      - POSTGRES_DB_PASSWORD=password

volumes:
  sso_pg_data:
  todo_pg_data: