services:
  todo-db:
    image: postgres:latest
    container_name: todo-db
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
  todo:
    build: todo
    container_name: todo
    ports:
      - "8080:8080"
    depends_on:
      - sso
      - todo-db
  sso-db:
    image: postgres:latest
    container_name: sso-db
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sso
    ports:
      - "5433:5432"
    volumes:
      - sso_pg_data:/var/lib/postgresql/data
  sso:
    build: sso
    container_name: sso
    ports:
      - "8081:8080"
    depends_on:
      - sso-db
volumes:
  sso_pg_data:
  todo_pg_data: