env: 'local'
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
postgres_db:
  host: "127.0.0.1"
  port: "5432"
  db_name: "postgres"
  username: "postgres"
  password: "root"

